Skip fluent-plugin-geoblipper, which now requires a newer Ruby
This appears to be a certified plugin. If the upstream fluentd image
gets a newer ruby and I haven't noticed, please open an issue on
github.

ERROR:  Error installing fluent-plugin-geoblipper:
	dry-validation requires Ruby version >= 2.4.0.